apiVersion: v1
kind: Namespace
metadata:
  name: argo
---
# We install the "Quick Start" version of Argo Workflows
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows-upstream
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/argoproj/argo-workflows
    targetRevision: v3.5.2
    path: manifests/quick-start/minimal
  destination:
    server: https://kubernetes.default.svc
    namespace: argo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true